#!/usr/bin/env bash
# Raven - UserBot


if [ -d "resources" ]
then
    echo "Current directory Identified.."
else
    apt install git -y
    git clone https://github.com/itzNightmare17/Raven
    cd Raven
fi

printf "Updating System..\n\n"
pkg update -y
apt update
apt upgrade -y

python_not_installed="$(python -c 'exit()')"

# Install Python if n0t installed..
if [ python_not_installed ]
then
    printf "Installing Python..\nThis may take some long...\n"
    pkg install python3 -y
fi

printf "*Putting some magical effect...*"
pip install -q colorama

printf "Running up Installation tool.\n"
python resources/extras/_termux.py
