#!/usr/bin/env bash
# Raven - UserBot


if [ -d "resources" ]
then
    echo "Current directory Identified.."
else
    apt install git -y
    git clone https://github.com/itzNightmare17/Raven
    cd Raven
fi
bash resources/startup/termux.sh
